CREATE TABLE LOCAL_POPULATION (
    "ID" SMALLINT NOT NULL,
    "ZIP_CODE" INT NOT NULL,
    "POPULATION" INT NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE DEMOGRAPHICS (
    "CUSTOMER_ID" VARCHAR(10) NOT NULL,
    "COUNT" SMALLINT NOT NULL,
    "GENDER" VARCHAR(6) NOT NULL,
    "AGE" SMALLINT NOT NULL,
    "UNDER_30" VARCHAR(3) NOT NULL,
    "IS_SENIOR" VARCHAR(3) NOT NULL,
    "IS_MARRIED" VARCHAR(3) NOT NULL,
    "HAS_DEPENDENTS" VARCHAR(3) NOT NULL,
    "N_DEPENDENTS" SMALLINT NOT NULL,
    PRIMARY KEY ("CUSTOMER_ID")
);

CREATE TABLE LOCATION (
    "LOCATION_ID" VARCHAR(10) NOT NULL,
    "CUSTOMER_ID" VARCHAR(10) NOT NULL,
    "COUNT" SMALLINT NOT NULL,
    "COUNTRY" VARCHAR(13) NOT NULL,
    "STATE" VARCHAR(15) NOT NULL,
    "CITY" VARCHAR(50) NOT NULL,
    "ZIP_CODE" INT NOT NULL,
    "LAT_LONG" VARCHAR(25) NOT NULL,
    "LATITUDE" FLOAT NOT NULL,
    "LONGITUDE" FLOAT NOT NULL,
    PRIMARY KEY ("CUSTOMER_ID")
);

CREATE TABLE SERVICES (
    "SERVICE_ID" VARCHAR(15) NOT NULL,
    "CUSTOMER_ID" VARCHAR(10) NOT NULL,
    "COUNT" SMALLINT NOT NULL,
    "QUARTER" VARCHAR(2) NOT NULL,
    "REFERRED_A_FRIEND" VARCHAR(3) NOT NULL,
    "N_REFERRED" SMALLINT NOT NULL,
    "MONTHS_TENURE" SMALLINT NOT NULL,
    "OFFER" VARCHAR(10) NOT NULL,
    "PHONE_SERVICE" VARCHAR(3) NOT NULL,
    "AVG_MONTHLY_LONG_DIST_CHARGE" FLOAT NOT NULL,
    "MULTIPLE_LINES" VARCHAR(3) NOT NULL,
    "INTERNET_SERVICE" VARCHAR(3) NOT NULL,
    "INTERNET_TYPE" VARCHAR(12) NOT NULL,
    "AVG_MONTHLY_GB_DOWN" SMALLINT NOT NULL,
    "ONLINE_SECURITY" VARCHAR(3) NOT NULL,
    "ONLINE_BACKUP" VARCHAR(3) NOT NULL,
    "DEVICE_PROTECTION" VARCHAR(3) NOT NULL,
    "PREMIUM_TECH_SUPPORT" VARCHAR(3) NOT NULL,
    "STREAMING_TV" VARCHAR(3) NOT NULL,
    "STREAMING_MOVIES" VARCHAR(3) NOT NULL,
    "STREAMING_MUSIC" VARCHAR(3) NOT NULL,
    "UNLIMITED_DATA" VARCHAR(3) NOT NULL,
    "CONTRACT_TYPE" VARCHAR(14) NOT NULL,
    "PAPERLESS_BILLING" VARCHAR(3) NOT NULL,
    "PAYMENT_METHOD" VARCHAR(15) NOT NULL,
    "MONTHLY_CHARGE" FLOAT NOT NULL,
    "TOTAL_CHARGE" FLOAT NOT NULL,
    "TOTAL_REFUNDS" FLOAT NOT NULL,
    "TOTAL_EXTRA_DATA_CHARGES" FLOAT NOT NULL,
    "TOTAL_LONG_DIST_CHARGES" FLOAT NOT NULL,
    "TOTAL_REVENUE" FLOAT NOT NULL,
    PRIMARY KEY ("CUSTOMER_ID")
);

CREATE TABLE STATUS (
    "STATUS_ID" VARCHAR(10) NOT NULL,
    "CUSTOMER_ID" VARCHAR(10) NOT NULL,
    "COUNT" SMALLINT NOT NULL,
    "QUARTER" VARCHAR(2) NOT NULL,
    "SATISFACTION_SCORE" SMALLINT NOT NULL,
    "CUSTOMER_STATUS" VARCHAR(7) NOT NULL,
    "CHURN_LABEL" VARCHAR(3) NOT NULL,
    "CHURN_VALUE" BOOLEAN NOT NULL,
    "CHURCH_SCORE" SMALLINT NOT NULL,
    "CLTV" SMALLINT NOT NULL,
    "CHURN_CATEGORY" VARCHAR(64),
    "CHURN_REASON" VARCHAR(256),
    PRIMARY KEY ("CUSTOMER_ID")
)